name 'ts_basebox'
description ''
maintainer 'Timo Schmidt'
license ''
version '0.1.2'

depends 'apt', '= 2.3.10'
depends 'apache2', '= 3.0.0'
depends 'mysql', '= 5.6.1'
depends 'composer', '= 1.1.0'
depends 'hostsfile', '= 2.4.5'
depends 'java', '= 1.7.0'
depends 'elasticsearch', '= 0.3.13'
depends 'solr', '= 0.5.0'
