name 'ts_basebox'
description ''
maintainer 'Timo Schmidt'
license ''
version '0.0.1'

depends 'apt'
depends 'apache2'
depends 'mysql'
depends 'composer'
depends 'hostsfile'
depends 'java'
depends 'elasticsearch'
depends 'solr'
